print("Persona: Hola, gatito. ¿Cómo estás hoy?")
print("Gato:    Miau, estoy bien. ¿Y tú?")
print("Persona: Estoy bien también. ¿Qué has hecho hoy?")
print("Gato:    He dormido mucho y he mirado por la ventana. ¿Y tú?")
print("Persona: He trabajado un poco y ahora estoy descansando. ¿Tienes hambre?")
print("Gato:    Miau, siempre tengo hambre. ¿Me das algo de comer?")
print("Persona: Claro, te daré un poco de comida. ¿Algo más que necesites?")
print("Gato:    No, solo un poco de cariño después de comer.")
print("Persona: Por supuesto, gatito. Bueno, me tengo que ir al trabajo.")
print("Gato:    Miau, está bien. Nos vemos luego.")
print("Persona: Adiós, gatito.")
print("Gato:    Miau, adiós.")
